### ISSUE TITLE
HyVideoFlowEditSampler node missing in example workflow

### ISSUE THREAD

**Issue by johhnry** [logtd/ComfyUI-HunyuanLoom#3]
Hi,

I just installed [ComfyUI wrapper nodes for HunyuanVideo](https://github.com/kijai/ComfyUI-HunyuanVideoWrapper/tree/main) and opening the workflow [example_hunyuan_flowedit.json](https://github.com/logtd/ComfyUI-HunyuanLoom/blob/main/example_workflows/example_hunyuan_flowedit.json) says that the only missing node is `HyVideoFlowEditSampler`.

I can't find anything online about that node. Where does it come from?

Thanks

**Comment by logtd** [comment]
Hi, just to make sure did you also install this node pack?

**Comment by johhnry** [comment]
@logtd thanks for the answer, my bad it works now!

**Comment by songyang86** [comment]
@johhnry how to  install this node pack?

**Comment by jacnav** [comment]
hi, im having the same issue, what node pack are you referring to please
